# -*- coding: utf-8 -*-
"""sales_eda

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C-EwDO3hYdU_M8SqwZZpWebXG10SUWjn
"""

#Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset
from google.colab import files
uploaded = files.upload()

import pandas as pd
# Step 3: Read Your sales_data.csv
df= pd.read_csv('sales_data.csv',encoding='latin1')
df.head()

# Basic info about dataset
df.info()

# Check for missing values
df.isnull().sum()

# See basic statistics
df.describe()

# Check column names
df.columns

#Sales Distribution – Histogram

plt.figure(figsize=(8,5))
sns.histplot(df['Sales'],bins=30,kde=True)
plt.title('Sales Distribution')
plt.xlabel('sales Amount')
plt.ylabel('Count')
plt.show()

#Profit vs Sales – Scatter Plot

plt.figure(figsize=(8,5))
sns.scatterplot(data=df, x='Sales', y='Profit', hue='Category')
plt.title('Profit Vs Sales by Category')
plt.xlabel('Sales')
plt.ylabel('Profit')
plt.show

# Total Sales by Category – Bar Chart
category_sales = df.groupby('Category')['Sales'].sum().reset_index()

plt.figure(figsize=(8,5))
sns.barplot(data=category_sales,x='Category',y='Sales')
plt.title('Total Sales by Category')
plt.ylabel('Total Sales')
plt.show()

# Correlation matrix
corr = df.corr(numeric_only=True)

# Plot heatmap
plt.figure(figsize=(8,5))
sns.heatmap(corr,annot=True,cmap='coolwarm',fmt=".2f")
plt.title("Correlation matrix")
plt.show()

# Profit vs Discount
plt.figure(figsize=(8,5))
sns.scatterplot(data=df,x='Discount',y='Profit')
plt.title("Profit Vs Discount")
plt.show()

# Regionalwise sales
region_sales=df.groupby('Region')['Sales'].sum().reset_index()
plt.figure(figsize=(8,5))

sns.barplot(data=region_sales,x='Region',y='Sales')
plt.title('Region-wise Sales')
plt.ylabel='Total Sales'
plt.show()

# Quantity Vs Profit
plt.figure(figsize=(8,5))
sns.scatterplot(data=df,x='Profit',y='Quantity')
plt.show()

# Correlation Heatmap
# Let’s calculate and visualize the correlation between key numerical features:

# Sales

# Profit

# Discount

# Quantity
numeric_data=df[['Sales','Profit','Discount','Quantity']]

plt.figure(figsize=(8,5))
corr2=numeric_data.corr()
sns.heatmap(corr2,annot=True,cmap='coolwarm',linewidths=0.5)
plt.title('Correlation Heatmap')
plt.show